env:
  browser: true
  node: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "no-unused-vars": [
  'warn',{ 
    argsIgnorePattern: '_',
    varsIgnorePattern: '_',
    caughtErrorsIgnorePattern: '_',
  },
],
}
